[project]
name = "subscription-finder"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.4.2",
    "pandas>=2.3.3",
    "rich>=14.2.0",
]
